function getRandomGreeting() {
  var greetings = [
    "Beep boop! Are you a robot?",
    "first week of school was boring",
    "once upon a time jonathan osorio was born",
    "if you look at this text u gay",
    "Made you look!",
    "dating isn't everything",
    "I am not a girl",
    "imagine being a Chinese old man living in the mountains",
    "the seal is the real deal",
    "destiny going crazy in those debates W",
    "William lane craig is pretty smart",
    "Made by Jonathan osorio!",
    "Reload the page NOW!",
    "Downloading your history...",
    "hacking your wascohusd.org password rn",
    "I'm a pro life",
    "be happy, be nice, be courage",
    "I hate everybody(jk)",
    "i am born on may 3rd 2010",
    "when will I meet someone as smart as me",
    "Powered by cotton technology",
    "war is so so so so much worse than you think",
    "I wish that girl best of lucksksd-sd",
    "I think islam is false",
    "im typnig thiss  with my njose ",
    "i will never understand atheists",
    "give jonathan osorio all ur money for unblocked youtube",
    "ima drop out of high school watch",
    "follow God not religion",
    "william lane craig on TOP",
    "Powered by 16MB of RAM!",
    "i am not real",
    "wascoooo highhh schoolll wascooo californiaaaa united states of americaaaa",
    "w h a t",
    "racist jokes are not funny no more",
    "Please be a good person",
    "win the battle against weed with GOD",
    "message me on my ig for more games",
    "thx stackoverflow!",
    "if i add more games on here ur chromebook will be too slow",
    "It is time to get funky!",
    "We didn't start the fire! It was always burning, since the world's been turning!",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Microsoft Edge, you need some help.",
    "people say they believe in God but i see no attempt in them trying to live sinlessly",
    "Shoutout to Fabritzio for his hospitality and Antonio ofc",
    "Shoutout to Jonathan Osorio thats me btw",
    "i feel so much existential dread but i hide it all with my silliness!",
    "do people actually read this",
    "heck yeah man!",
    "i used to be so immature and im ashamed of my past",
    "heheeeeee",
    "POV that one person who's 2 braincells are fighting for second place.",
    "2024 is chaotic but every year is chaotic",
    "wasco high school is lowkey trash ",
    "No fun allowed",
    " gulp",
    "i do love buying birth certificates from the black market",
    "'it is the pinnacle of all human emotion. More passionate than hope, far deeper from despair. Love' - homura",
    "Im kinda sped",
    "i want money so i can buy stuff",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for another message",
    "i love philosophy",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "woahhh",
    "this website took me 15 hours to create btw",
    "Trust me, I did not copy Minecraft with this",
    "a man is not just a good looking object",
    "love purely",
    "LOVE",
    "more love less violence",
    "You bum",
    "a women is not just a good looking object ",
    "life is meaningless without victories",
    "i think im better than fabritzio at soccer",
    "erm",
    "I spent too much time making these",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
