function getRandomGreeting() {
  var greetings = [
    "Beep boop! Are you a robot?",
    "Wasco high school is not so cool",
    "im lost",
    "GOD IS REALLL",
    "Made you look!",
    "JONATHAN OSORIO IS SUPER COOOOL",
    "Antonio Rosas is cool ",
    "Fabritzio is cool and his partnerr",
    "The second i turn atheist im ending my life",
    "atheists are under a subjective illusion",
    "no God or creator means no objective meaning to life",
    "Made by Jonathan osorio!",
    "Reload the page NOW!",
    "Downloading your passwords...",
    "hacking your passwords rn",
    "this website is so simple",
    "The reason this website is so bland is because the school computers are so slow so it wouldnt keep up if i made it more complicated 😭",
    "self love is narcissm",
    "im 14 years old",
    "is thinking critically illegal",
    "Powered by hamsterwheel technology",
    "kabooommmm",
    "reh ssim i",
    "I think islam is false",
    "friedrich nietzsche on top ",
    "i will never understand atheists",
    "give jonathan osorio all ur money for unblocked youtube",
    "i wanna be a web developer",
    "follow God not religion",
    "william lane craig on TOP",
    "Powered by 16MB of RAM!",
    "i am not real",
    "wascoooo highhh schoolll wascooo californiaaaa united states of americaaaa",
    "w h a t",
    "racist jokes are not funny no more",
    "Please be a good person",
    "win the battle against weed with GOD",
    "message me on my ig for more games",
    "thx stackoverflow!",
    "if i add more games on here ur chromebook will be too slow",
    "It is time to get funky!",
    "We didn't start the fire! It was always burning, since the world's been turning!",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Microsoft Edge, you need some help.",
    "people say they believe in God but i see no attempt in them trying to live sinlessly",
    "Shoutout to Fabritzio for his hospitality and Antonio ofc",
    "Shoutout to Jonathan Osorio thats me btw",
    "interesting",
    "do people actually read this",
    "instagram.com/j.srio",
    "i used to be so immature and im ashamed of my past",
    "We've Been Trying To Reach You About Your Car's Extended Warranty",
    "POV that one person who's 2 braincells are fighting for second place.",
    "2024 is chaotic but every year is chaotic",
    "RFK JR FOR PRESIDENTTTTTT and maybe vermin supreme too chat",
    "No fun allowed",
    "BRAYAN OSORIO PEREZ(i think its perez) IS PRETTY COOL",
    "i do love buying birth certificates from the black market",
    "'it is the pinnacle of all human emotion. More passionate than hope, far deeper from despair.Love' - homura",
    "i feel dumb sometimes",
    "i want money so i can buy stuff",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for another message",
    "i love philosophy",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "woahhh",
    "this website took me 15 hours to create btw",
    "Trust me, I did not copy Minecraft with this",
    "i dont know what to write",
    "love purely",
    "LOVE",
    "more love less violence",
    "You bum",
    "a women is not just a good looking object ",
    "i wanna be good at soccer",
    "i think im better than fabritzio at soccer",
    "elon musk is smart",
    "I spent too much time making these",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
